Add check if dotfiles is set

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -39,7 +39,14 @@ while test $# -gt 0; do
 done
 
 export DOTFILES=$(set_dotfiles_dir)
-echo "Setting dotfiles dir to: ${DOTFILES}"
+
+if DOTFILES
+then
+  echo "Setting dotfiles dir to: ${DOTFILES}"
+else
+  echo "Couldn't determine dotfiles dir"
+  exit 1
+fi
 
 if [ "$(uname -s)" == "Darwin" ]
 then
